### ISSUE TITLE
Disables more than just the clock

### ISSUE THREAD

**Issue by johnholliday** [thomasclaudiushuber/HideIconTray#1]
Hiding the system tray (clock) also disables the icons in the taskbar corner (they are visible, but not clickable).  Is there a way to target just the clock?

**Comment by thomasclaudiushuber** [comment]
Hey @johnholliday, I was not able to grab just the clock, as it is an inner component of the icon tray that I couldn't grab from outside. But I guess and hope that at some point, we'll get that feature natively in Windows 11.
